# Generated by Django 4.0.6 on 2022-07-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fieldtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=7)),
                ('stock', models.IntegerField(max_length=4)),
            ],
        ),
    ]
